#!/usr/bin/env bash
# Single-source the deterministic scripts. Canonical = prism-all/*.
# prism-codex and prism receive generated copies. Run after editing a canonical.
#
# parse-findings.js + verify-evidence.js are byte-identical across skills → plain copy.
# verify-independence.js differs per skill (SELF_NAME / PREREQUISITES), so it is
# generated by a sed rewrite of the canonical rather than copied verbatim.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"

# 1. Identical scripts: copy verbatim.
for f in parse-findings.js verify-evidence.js; do
  cp "$here/prism-all/$f" "$here/prism-codex/$f"
  cp "$here/prism-all/$f" "$here/prism/$f"
done

# 2. verify-independence.js: prism-codex = rename only; prism = rename + drop Codex prereq.
sed 's/prism-all/prism-codex/g' "$here/prism-all/verify-independence.js" > "$here/prism-codex/verify-independence.js"
sed 's/prism-all/prism/g' "$here/prism-all/verify-independence.js" \
  | perl -0pe "s/const PREREQUISITES = \[\n  \{ cmd: 'codex --version', label: 'Codex CLI', fatal: true, min: '0\.125\.0' \},\n\];/const PREREQUISITES = []; \/\/ prism is Claude-only — no external CLI prerequisite/" \
  > "$here/prism/verify-independence.js"

# 3. Verify the sync actually holds (integrity gate — catches silent drift).
fail=0
for f in parse-findings.js verify-evidence.js; do
  for d in prism-codex prism; do
    if ! diff -q "$here/prism-all/$f" "$here/$d/$f" >/dev/null; then
      echo "DRIFT: $d/$f != prism-all/$f" >&2; fail=1
    fi
  done
done
[ "$fail" = 0 ] && echo "synced + verified: parse-findings.js, verify-evidence.js, verify-independence.js -> prism-codex, prism" || { echo "sync FAILED" >&2; exit 1; }
